# Generated by Django 5.0.3 on 2024-03-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootballApp', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('pais', models.CharField(max_length=25)),
                ('division', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='player',
            old_name='country',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='team',
            new_name='equipo',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='first_name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='last_name',
            new_name='pais',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='position',
            new_name='posicion',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='league',
            new_name='liga',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='country',
            new_name='pais',
        ),
    ]
