# Generated by Django 5.0.3 on 2024-03-24 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FootballApp', '0003_league_tournament_rename_country_player_apellido_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
