# Generated by Django 5.0.3 on 2024-03-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootballApp', '0004_delete_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('numero_de_equipos', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='league',
            name='division',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.PositiveIntegerField(),
        ),
    ]
