# Generated by Django 5.0.3 on 2024-03-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootballApp', '0007_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='apellido',
        ),
        migrations.AlterField(
            model_name='player',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
